services:
  postgres:
    image: postgres:16
    container_name: marocsphere-db
    environment:
      POSTGRES_DB: marocsphere
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      network: host
    container_name: marocsphere-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
