// Moroccan AI Travel Hub — Shared Script
// Generated by UXMagic Copilot

document.addEventListener('DOMContentLoaded', function () {
  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      var target = document.querySelector(this.getAttribute('href'));
      if (target) { e.preventDefault(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
    });
  });

  // Prevent default form submit
  document.querySelectorAll('form').forEach(function (form) {
    form.addEventListener('submit', function (e) { e.preventDefault(); });
  });

  // ── Client Dashboard & AI Planner the name of the brand is MarocSphere ──
  (function initPage_client_dashboard_ai_planner_the_name_of_the_brand_is_marocsphere() {
    // Inline scripts from original page (scoped to this page's wrapper):
    /**
     * Rewrites viewport-relative CSS units (vh, dvh, svh, lvh) to pixel values
     * based on the frame's design viewport height.
     *
     * Canvas iframes are sized to the full document height for auto-fit, which
     * inflates raw `vh` units. Converting to px once breaks the feedback loop and
     * keeps layouts stable when the iframe grows.
     */
    (function () {
      var DESIGN_H = 1024 || 1024;
      var VH_PX = DESIGN_H / 100;
      var VH_UNIT_RE = /(-?[\d.]+)(vh|dvh|svh|lvh)\b/g;
      var patchedStyles = typeof WeakSet !== 'undefined' ? new WeakSet() : null;
      var patchedStyleTags = typeof WeakSet !== 'undefined' ? new WeakSet() : null;
    
      function convertVhString(value) {
        VH_UNIT_RE.lastIndex = 0;
        return value.replace(VH_UNIT_RE, function (_match, num) {
          return String(parseFloat(num) * VH_PX) + 'px';
        });
      }
    
      function containsVhUnit(value) {
        VH_UNIT_RE.lastIndex = 0;
        return VH_UNIT_RE.test(value);
      }
    
      function patchStyleDeclaration(style) {
        if (!style) return false;
        if (patchedStyles && patchedStyles.has(style)) return false;
    
        var changed = false;
        for (var i = style.length - 1; i >= 0; i--) {
          var prop = style[i];
          var val = style.getPropertyValue(prop);
          if (containsVhUnit(val)) {
            style.setProperty(
              prop,
              convertVhString(val),
              style.getPropertyPriority(prop),
            );
            changed = true;
          }
        }
    
        if (changed && patchedStyles) patchedStyles.add(style);
        return changed;
      }
    
      function patchCssRules(rules) {
        if (!rules) return;
        for (var i = 0; i < rules.length; i++) {
          var rule = rules[i];
          if (rule.style) patchStyleDeclaration(rule.style);
          if (rule.cssRules) patchCssRules(rule.cssRules);
        }
      }
    
      function patchStyleElement(el) {
        if (!el || el.tagName !== 'STYLE') return;
        if (patchedStyleTags && patchedStyleTags.has(el)) return;
    
        var text = el.textContent || '';
        if (!containsVhUnit(text)) return;
    
        el.textContent = convertVhString(text);
        if (patchedStyleTags) patchedStyleTags.add(el);
      }
    
      function patchInlineStyles() {
        var nodes = document.querySelectorAll('[style*="vh"]');
        for (var i = 0; i < nodes.length; i++) {
          var el = nodes[i];
          var raw = el.getAttribute('style');
          if (!raw || !containsVhUnit(raw)) continue;
          el.setAttribute('style', convertVhString(raw));
        }
      }
    
      function patchAll() {
        var styleTags = document.querySelectorAll('style');
        for (var i = 0; i < styleTags.length; i++) {
          patchStyleElement(styleTags[i]);
        }
    
        for (var j = 0; j < document.styleSheets.length; j++) {
          try {
            patchCssRules(document.styleSheets[j].cssRules);
          } catch (_e) {
            // Inaccessible cross-origin stylesheet — skip.
          }
        }
    
        patchInlineStyles();
        window.__uxmVhFixApplied = true;
        try {
          window.dispatchEvent(new CustomEvent('uxm-vh-fix-applied'));
        } catch (_e) {}
      }
    
      var scheduled = null;
      function schedulePatch() {
        if (scheduled != null) return;
        scheduled = window.requestAnimationFrame
          ? window.requestAnimationFrame(function () {
              scheduled = null;
              patchAll();
            })
          : setTimeout(function () {
              scheduled = null;
              patchAll();
            }, 0);
      }
    
      if (typeof MutationObserver !== 'undefined') {
        new MutationObserver(schedulePatch).observe(document.documentElement, {
          childList: true,
          subtree: true,
          characterData: true,
        });
      }
    
      patchAll();
    
      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', patchAll);
      }
      window.addEventListener('load', patchAll);
    })();
  })();

  // ── Data Superadmin Analytics ──
  (function initPage_data_superadmin_analytics() {
    // Inline scripts from original page (scoped to this page's wrapper):
    setTimeout(() => {
          // Monthly Volume Chart
          const monthlyCtx = document.getElementById('monthlyVolumeChart');
          if (monthlyCtx) {
            new Chart(monthlyCtx, {
              type: 'line',
              data: {
                labels: ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
                datasets: [
                  {
                    label: 'Escrow Holdings',
                    data: [120000, 150000, 210000, 180000, 240000, 284500],
                    borderColor: '#9D3E26',
                    backgroundColor: 'rgba(157, 62, 38, 0.1)',
                    tension: 0.4,
                    fill: true
                  },
                  {
                    label: 'Released Funds',
                    data: [340000, 420000, 510000, 680000, 790000, 842900],
                    borderColor: '#1661A1',
                    backgroundColor: 'rgba(22, 97, 161, 0.1)',
                    tension: 0.4,
                    fill: true
                  }
                ]
              },
              options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                  legend: { display: false }
                },
                scales: {
                  y: { grid: { color: '#E3DFD5' }, ticks: { color: '#5A5C5E' } },
                  x: { grid: { display: false }, ticks: { color: '#5A5C5E' } }
                }
              }
            });
          }
    
          // Booking Distribution Chart
          const bookingCtx = document.getElementById('bookingDistributionChart');
          if (bookingCtx) {
            new Chart(bookingCtx, {
              type: 'doughnut',
              data: {
                labels: ['Artisan Crafts', 'Local Guides', 'DMC Packages', 'Transport'],
                datasets: [{
                  data: [45, 25, 20, 10],
                  backgroundColor: ['#9D3E26', '#1661A1', '#E3DFD5', '#5A5C5E'],
                  borderWidth: 2,
                  borderColor: '#FFFFFF'
                }]
              },
              options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                  legend: {
                    position: 'bottom',
                    labels: { color: '#2D2E30', font: { family: 'Inter' } }
                  }
                }
              }
            });
          }
        }, 100);
  })();

  // ── Multi-Role Authentication ──
  (function initPage_multi_role_authentication() {
    // Inline scripts from original page (scoped to this page's wrapper):
    /**
     * Rewrites viewport-relative CSS units (vh, dvh, svh, lvh) to pixel values
     * based on the frame's design viewport height.
     *
     * Canvas iframes are sized to the full document height for auto-fit, which
     * inflates raw `vh` units. Converting to px once breaks the feedback loop and
     * keeps layouts stable when the iframe grows.
     */
    (function () {
      var DESIGN_H = 1024 || 1024;
      var VH_PX = DESIGN_H / 100;
      var VH_UNIT_RE = /(-?[\d.]+)(vh|dvh|svh|lvh)\b/g;
      var patchedStyles = typeof WeakSet !== 'undefined' ? new WeakSet() : null;
      var patchedStyleTags = typeof WeakSet !== 'undefined' ? new WeakSet() : null;
    
      function convertVhString(value) {
        VH_UNIT_RE.lastIndex = 0;
        return value.replace(VH_UNIT_RE, function (_match, num) {
          return String(parseFloat(num) * VH_PX) + 'px';
        });
      }
    
      function containsVhUnit(value) {
        VH_UNIT_RE.lastIndex = 0;
        return VH_UNIT_RE.test(value);
      }
    
      function patchStyleDeclaration(style) {
        if (!style) return false;
        if (patchedStyles && patchedStyles.has(style)) return false;
    
        var changed = false;
        for (var i = style.length - 1; i >= 0; i--) {
          var prop = style[i];
          var val = style.getPropertyValue(prop);
          if (containsVhUnit(val)) {
            style.setProperty(
              prop,
              convertVhString(val),
              style.getPropertyPriority(prop),
            );
            changed = true;
          }
        }
    
        if (changed && patchedStyles) patchedStyles.add(style);
        return changed;
      }
    
      function patchCssRules(rules) {
        if (!rules) return;
        for (var i = 0; i < rules.length; i++) {
          var rule = rules[i];
          if (rule.style) patchStyleDeclaration(rule.style);
          if (rule.cssRules) patchCssRules(rule.cssRules);
        }
      }
    
      function patchStyleElement(el) {
        if (!el || el.tagName !== 'STYLE') return;
        if (patchedStyleTags && patchedStyleTags.has(el)) return;
    
        var text = el.textContent || '';
        if (!containsVhUnit(text)) return;
    
        el.textContent = convertVhString(text);
        if (patchedStyleTags) patchedStyleTags.add(el);
      }
    
      function patchInlineStyles() {
        var nodes = document.querySelectorAll('[style*="vh"]');
        for (var i = 0; i < nodes.length; i++) {
          var el = nodes[i];
          var raw = el.getAttribute('style');
          if (!raw || !containsVhUnit(raw)) continue;
          el.setAttribute('style', convertVhString(raw));
        }
      }
    
      function patchAll() {
        var styleTags = document.querySelectorAll('style');
        for (var i = 0; i < styleTags.length; i++) {
          patchStyleElement(styleTags[i]);
        }
    
        for (var j = 0; j < document.styleSheets.length; j++) {
          try {
            patchCssRules(document.styleSheets[j].cssRules);
          } catch (_e) {
            // Inaccessible cross-origin stylesheet — skip.
          }
        }
    
        patchInlineStyles();
        window.__uxmVhFixApplied = true;
        try {
          window.dispatchEvent(new CustomEvent('uxm-vh-fix-applied'));
        } catch (_e) {}
      }
    
      var scheduled = null;
      function schedulePatch() {
        if (scheduled != null) return;
        scheduled = window.requestAnimationFrame
          ? window.requestAnimationFrame(function () {
              scheduled = null;
              patchAll();
            })
          : setTimeout(function () {
              scheduled = null;
              patchAll();
            }, 0);
      }
    
      if (typeof MutationObserver !== 'undefined') {
        new MutationObserver(schedulePatch).observe(document.documentElement, {
          childList: true,
          subtree: true,
          characterData: true,
        });
      }
    
      patchAll();
    
      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', patchAll);
      }
      window.addEventListener('load', patchAll);
    })();
  })();
});

window.UIUtils = {
  toggleElement: function (selector) {
    var el = document.querySelector(selector);
    if (el) el.style.display = el.style.display === 'none' ? '' : 'none';
  },
};
