// MarocSphere Tourism Ecosystem — Shared Script
// Generated by UXMagic Copilot

document.addEventListener('DOMContentLoaded', function () {
  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      var target = document.querySelector(this.getAttribute('href'));
      if (target) { e.preventDefault(); target.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
    });
  });

  // Prevent default form submit
  document.querySelectorAll('form').forEach(function (form) {
    form.addEventListener('submit', function (e) { e.preventDefault(); });
  });

  // ── Super Admin Operations Dashboard ──
  (function initPage_super_admin_operations_dashboard() {
    // Inline scripts from original page (scoped to this page's wrapper):
    setTimeout(() => {
                  const ctx = document.getElementById('adminMetricsChart');
                  if (ctx) {
                    new Chart(ctx, {
                      type: 'line',
                      data: {
                        labels: ['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'],
                        datasets: [
                          {
                            label: 'Secure Escrow Volume',
                            data: [800000, 1100000, 1300000, 1500000, 1700000, 1800000],
                            borderColor: '#B63739',
                            backgroundColor: 'rgba(182, 55, 57, 0.1)',
                            borderWidth: 2,
                            fill: true,
                            tension: 0.4
                          },
                          {
                            label: 'Released Payouts',
                            data: [600000, 850000, 1000000, 1200000, 1350000, 1500000],
                            borderColor: '#006233',
                            backgroundColor: 'rgba(0, 98, 51, 0.1)',
                            borderWidth: 2,
                            fill: true,
                            tension: 0.4
                          }
                        ]
                      },
                      options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        plugins: {
                          legend: {
                            position: 'bottom',
                            labels: {
                              font: { size: 11, family: 'Plus Jakarta Sans' },
                              color: '#665E54'
                            }
                          }
                        },
                        scales: {
                          y: {
                            grid: { color: '#EFEAE2' },
                            ticks: { color: '#665E54', font: { size: 10 } }
                          },
                          x: {
                            grid: { display: false },
                            ticks: { color: '#665E54', font: { size: 10 } }
                          }
                        }
                      }
                    });
                  }
                }, 50);
  })();
});

window.UIUtils = {
  toggleElement: function (selector) {
    var el = document.querySelector(selector);
    if (el) el.style.display = el.style.display === 'none' ? '' : 'none';
  },
};
